const config_url = {
    ADD_USER_URL: process.env.ADD_USER_REGULAR_URL,
    GET_USER_VIP_URL: process.env.GET_VIP_USER_URL,
    GET_USER_CHART_DATA_URL: process.env.GET_REGULAR_BOOK_DATA_CHART,
    GET_BILL_USER_URL: process.env.GET_BILL_DATA_CHART,
    GET_BILL_THREE_USER_URL: process.env.GET_BILL_THREE_DATA_CHART,
    GET_AUCTION_BOOK_DATA_CHART_URL: process.env.GET_AUCTION_BOOK_DATA_CHART,
}

module.exports=config_url;